name: ci

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: pnpm/action-setup@v4
        with:
          version: ${{ vars.PNPM_VERSION }}
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODE_VERSION }}
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
      - run: pnpm run check
      - run: pnpm run build --site "https://${GITHUB_REPOSITORY##*/}"
      - name: Upload build artifact
        if: github.ref == 'refs/heads/main' || github.ref_type == 'tag'
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist
  deploy-to-github-pages:
    name: Deploy to GitHub Pages
    if: github.ref == 'refs/heads/main' || github.ref_type == 'tag'
    needs: [build]
    concurrency:
      cancel-in-progress: true
      group: "pages"
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      contents: read
      id-token: write
      pages: write
    runs-on: ubuntu-latest
    steps:
      - name: Deploy site
        id: deployment
        uses: actions/deploy-pages@v4
